#!/usr/bin/env python
from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent.citation_verifier import CitationVerifier
from agent.evidence_chain_tracer import EvidenceChainTracer
from agent.report_writer import CITATION_FIELDS
from agent.run_logging import EvidenceStore, ToolCallLogger
from agent.utils import clean_text, now_iso, timestamp_id, write_json


MODULE_SPEC = {
    "module_name": "DeepScientist Citation Hallucination Verification Module",
    "agent_style": "DeepScientist",
    "insertion_point": "after_hypothesis_generation_before_final_report",
    "purpose": (
        "Audit citation-backed claims generated by a DeepScientist-style research agent. "
        "The module checks whether cited papers exist, whether citation metadata matches "
        "public records, and whether available abstracts/snippets support the generated claim."
    ),
    "inputs": [
        "hypothesis_id",
        "claim_id",
        "claim_text",
        "cited_work.title",
        "cited_work.authors",
        "cited_work.year",
        "cited_work.doi",
    ],
    "outputs": [
        "citation_verification.csv",
        "evidence_chain.csv",
        "evidence_chain.md",
        "deepscientist_audit_summary.md",
        "deepscientist_module_manifest.json",
        "tool_calls.jsonl",
        "evidence_items.jsonl",
    ],
    "non_llm_boundary": (
        "Green/Yellow/Red labels are produced by deterministic verification logic and public "
        "scholarly API lookups, not by an LLM judgment."
    ),
}


class DeepScientistCitationAuditModule:
    """Adapter for using this project as a DeepScientist-style verification module.

    DeepScientist-style agents usually produce hypotheses plus supporting
    citations. This adapter exposes the citation-verification part as a
    standalone module that can be inserted after hypothesis generation.
    """

    def __init__(self, output_root: Path | None = None, timeout_seconds: int = 15):
        self.output_root = output_root or (ROOT / "outputs" / "deepscientist_audits")
        self.timeout_seconds = timeout_seconds

    def module_spec(self) -> dict[str, Any]:
        return dict(MODULE_SPEC)

    def audit_claims(
        self,
        claims: list[dict[str, Any]],
        *,
        run_dir: Path | None = None,
        source_payload: dict[str, Any] | None = None,
        source_name: str = "deepscientist_hypothesis_generation",
    ) -> dict[str, Any]:
        run_dir = (run_dir or self.output_root / timestamp_id()).resolve()
        run_dir.mkdir(parents=True, exist_ok=True)

        logger = ToolCallLogger(run_dir)
        evidence = EvidenceStore(run_dir)
        verifier = CitationVerifier(logger, evidence, timeout_seconds=self.timeout_seconds)
        tracer = EvidenceChainTracer(logger, evidence)

        receive_call_id = logger.next_id()
        started = time.perf_counter()
        normalized_claims = [self._normalize_claim(claim, idx + 1) for idx, claim in enumerate(claims)]
        write_json(run_dir / "deepscientist_module_manifest.json", self.module_spec())
        write_json(run_dir / "input_claims.json", {"claims": normalized_claims})
        if source_payload is not None:
            write_json(run_dir / "source_hypothesis_payload.json", source_payload)
        module_evidence_id = evidence.record(
            source_type="deepscientist_adapter",
            source=source_name,
            content_snippet=(
                f"Received {len(normalized_claims)} DeepScientist-style citation-backed claims "
                "for citation hallucination verification."
            ),
            category="module_input",
            tool_call_id=receive_call_id,
            locator="input_claims.json",
            metadata={"claim_count": len(normalized_claims)},
        )
        logger.log(
            tool_call_id=receive_call_id,
            tool_name="deepscientist_adapter.receive_hypothesis_claims",
            inputs={"source_name": source_name, "claim_count": len(normalized_claims)},
            status="success",
            output_summary=(
                "Received DeepScientist-style citation-backed claims for deterministic "
                "citation hallucination verification."
            ),
            started_at=started,
            outputs={
                "manifest": "deepscientist_module_manifest.json",
                "claims": "input_claims.json",
                "evidence_id": module_evidence_id,
            },
        )

        verification_rows = verifier.verify(normalized_claims)
        tracer.trace_and_write(
            run_dir,
            hypothesis_payload={"claims": normalized_claims},
            literature=[],
            verification_rows=verification_rows,
        )
        self._write_csv(run_dir / "citation_verification.csv", verification_rows)
        summary = self._render_summary(source_name, normalized_claims, verification_rows)
        (run_dir / "deepscientist_audit_summary.md").write_text(summary, encoding="utf-8")

        write_call_id = logger.next_id()
        write_started = time.perf_counter()
        counts = self._label_counts(verification_rows)
        logger.log(
            tool_call_id=write_call_id,
            tool_name="deepscientist_adapter.write_audit_outputs",
            inputs={"run_dir": str(run_dir)},
            status="success",
            output_summary=(
                f"Wrote DeepScientist citation audit outputs. "
                f"Green={counts['Green']} Yellow={counts['Yellow']} Red={counts['Red']}."
            ),
            started_at=write_started,
            outputs={
                "citation_verification_csv": str(run_dir / "citation_verification.csv"),
                "evidence_chain_csv": str(run_dir / "evidence_chain.csv"),
                "summary": str(run_dir / "deepscientist_audit_summary.md"),
            },
        )
        return {
            "run_dir": str(run_dir),
            "claims": normalized_claims,
            "verification_rows": verification_rows,
            "label_counts": counts,
            "summary": summary,
        }

    def audit_claims_file(self, claims_path: Path, *, run_dir: Path | None = None) -> dict[str, Any]:
        payload = json.loads(claims_path.read_text(encoding="utf-8-sig"))
        claims = payload.get("claims", payload if isinstance(payload, list) else [])
        if not isinstance(claims, list):
            raise ValueError("Claims file must be a list or a JSON object with a 'claims' list.")
        return self.audit_claims(
            claims,
            run_dir=run_dir,
            source_payload=payload if isinstance(payload, dict) else {"claims": payload},
            source_name=str(claims_path),
        )

    def _normalize_claim(self, claim: dict[str, Any], idx: int) -> dict[str, Any]:
        cited = claim.get("cited_work") or {}
        return {
            "claim_id": clean_text(claim.get("claim_id")) or f"C{idx:03d}",
            "claim_text": clean_text(claim.get("claim_text")),
            "hypothesis_id": clean_text(claim.get("hypothesis_id")) or "H_UNKNOWN",
            "claim_role": clean_text(claim.get("claim_role")) or "deepscientist_generated_claim",
            "cited_work": {
                "title": clean_text(cited.get("title")),
                "authors": cited.get("authors") or [],
                "year": cited.get("year") or "",
                "doi": clean_text(cited.get("doi")),
                "venue": clean_text(cited.get("venue")),
                "url": clean_text(cited.get("url")),
                "retrieval_source": clean_text(cited.get("retrieval_source")) or "deepscientist_output",
                "literature_id": cited.get("literature_id"),
                "evidence_id": cited.get("evidence_id"),
                "abstract": clean_text(cited.get("abstract")),
                "snippet": clean_text(cited.get("snippet")),
            },
        }

    def _write_csv(self, path: Path, rows: list[dict[str, Any]]) -> None:
        with path.open("w", newline="", encoding="utf-8-sig") as handle:
            writer = csv.DictWriter(handle, fieldnames=CITATION_FIELDS)
            writer.writeheader()
            for row in rows:
                writer.writerow({field: row.get(field, "") for field in CITATION_FIELDS})

    def _label_counts(self, rows: list[dict[str, Any]]) -> dict[str, int]:
        counts = {"Green": 0, "Yellow": 0, "Red": 0}
        for row in rows:
            label = row.get("color_label", "Red")
            counts[label] = counts.get(label, 0) + 1
        return counts

    def _render_summary(
        self,
        source_name: str,
        claims: list[dict[str, Any]],
        rows: list[dict[str, Any]],
    ) -> str:
        counts = self._label_counts(rows)
        lines = [
            "# DeepScientist Citation Hallucination Audit",
            "",
            f"Generated: {now_iso()}",
            f"Source: {source_name}",
            "",
            "## Module Position",
            "",
            "This module is inserted after DeepScientist-style hypothesis generation and before final report writing.",
            "It audits generated citation-backed claims rather than generating the final labels with an LLM.",
            "",
            "## Label Counts",
            "",
            f"- Green: {counts['Green']}",
            f"- Yellow: {counts['Yellow']}",
            f"- Red: {counts['Red']}",
            "",
            "## Verification Table",
            "",
            "| Claim ID | Hypothesis | Color | Exists | Metadata | Support | Reason |",
            "|---|---|---|---|---|---|---|",
        ]
        claim_by_id = {claim["claim_id"]: claim for claim in claims}
        for row in rows:
            claim = claim_by_id.get(row.get("claim_id"), {})
            lines.append(
                f"| {row.get('claim_id')} | {claim.get('hypothesis_id', '')} | {row.get('color_label')} | "
                f"{row.get('exists_status')} | {row.get('metadata_match_status')} | "
                f"{row.get('support_status')} | {self._cell(row.get('reason', ''))} |"
            )
        lines.extend(
            [
                "",
                "## Audit Boundary",
                "",
                "- Green requires existence, metadata match, and concrete support from title/abstract/snippet.",
                "- Yellow means the cited paper exists but support is partial or cannot be confirmed from public metadata.",
                "- Red means the citation is missing, mismatched, or not supported by available evidence.",
                "- LLM output may be used upstream for hypothesis wording, but this module's labels come from code and public API evidence.",
            ]
        )
        return "\n".join(lines)

    def _cell(self, text: Any) -> str:
        return clean_text(text).replace("|", "\\|")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Audit DeepScientist-style generated citations")
    parser.add_argument("--claims", required=True, help="Path to generated_claims.json or a claims JSON list")
    parser.add_argument("--run-dir", default=None, help="Explicit output directory")
    parser.add_argument(
        "--output-root",
        default=str(ROOT / "outputs" / "deepscientist_audits"),
        help="Output root when --run-dir is not provided",
    )
    parser.add_argument("--timeout-seconds", type=int, default=15)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    claims_path = Path(args.claims)
    if not claims_path.is_absolute():
        claims_path = (Path.cwd() / claims_path).resolve()
    if not claims_path.exists():
        print(f"ERROR: claims file not found: {claims_path}", file=sys.stderr)
        return 2
    run_dir = Path(args.run_dir).resolve() if args.run_dir else None
    module = DeepScientistCitationAuditModule(Path(args.output_root), timeout_seconds=args.timeout_seconds)
    result = module.audit_claims_file(claims_path, run_dir=run_dir)
    counts = result["label_counts"]
    print("DeepScientist citation audit complete")
    print(f"Run directory: {result['run_dir']}")
    print(f"Green={counts['Green']} Yellow={counts['Yellow']} Red={counts['Red']}")
    print("Key files:")
    print(f"- {Path(result['run_dir']) / 'citation_verification.csv'}")
    print(f"- {Path(result['run_dir']) / 'evidence_chain.csv'}")
    print(f"- {Path(result['run_dir']) / 'deepscientist_audit_summary.md'}")
    print(f"- {Path(result['run_dir']) / 'tool_calls.jsonl'}")
    print(f"- {Path(result['run_dir']) / 'evidence_items.jsonl'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
